// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv






import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    db: {
      provider: "postgresql",
      url: process.env.DATABASE_URL,
    },
  },
});


